title: Maximilian Sieb
bigimg: assets/profile_pic.jpg
theme: jekyll-theme-minimal
google_analytics: UA-133437620-1

social-network-links:
  rss: true
  email: msieb at covariant dot ai
  linkedin: https://www.linkedin.com/in/maximilian-sieb/
  google
