title: Maximilian Sieb
theme: jekyll-theme-minimal
logo: assets/profile_pic.jpg
description: 
  Research Engineer at Covariant
google_analytics: UA-133437620-1

# urls
urls:
    linkedin: "https://www.linkedin.com/in/maximilian-sieb/"
    github: "https://www.github.com/msieb1"
    scholar: "https://scholar.google.com/citations?user=RJ_c4xkAAAAJ&hl=en"
    twitter: "https://twitter.com/isobuten1"
