title: Maximilian Sieb
theme: jekyll-theme-minimal
logo: assets/profile_pic.jpg
description: 
  Research Engineer at Covariant \n
  MS Robotics, Carnegie Mellon University \n
  MS Computational Engineering, TU Darmstadt

google_analytics: UA-133437620-1
